-- Generated by Oracle SQL Developer Data Modeler 4.1.0.873
--   at:        2015-04-11 13:44:29 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g





CREATE TABLE Czas_Pracy
  (
    ID           INTEGER NOT NULL ,
    Data         DATE NOT NULL ,
    Czas         NUMBER NOT NULL ,
    Komentarz    VARCHAR2 (4000 BYTE) NOT NULL ,
    INSD         DATE NOT NULL ,
    MODD         DATE NOT NULL ,
    Pracownik_ID INTEGER NOT NULL ,
    Zadanie_ID   INTEGER NOT NULL ,
    INSP         INTEGER NOT NULL ,
    MODP         INTEGER NOT NULL
  ) ;
ALTER TABLE Czas_Pracy ADD CONSTRAINT Czas_Pracy_PK PRIMARY KEY ( ID ) ;

CREATE TABLE Klient
  (
    ID    INTEGER NOT NULL ,
    Kod   VARCHAR2 (16 CHAR) ,
    Nazwa VARCHAR2 (2048 CHAR) NOT NULL ,
    Uwagi VARCHAR2 (2048 CHAR)
  ) ;
ALTER TABLE Klient ADD CONSTRAINT Klient_PK PRIMARY KEY ( ID ) ;

CREATE TABLE Pracownik
  (
    ID       INTEGER NOT NULL ,
    Imie     VARCHAR2 (512 CHAR) NOT NULL ,
    Nazwisko VARCHAR2 (512 CHAR) NOT NULL ,
    PESEL    VARCHAR2 (24 CHAR) NOT NULL ,
    Uwagi    VARCHAR2 (2048 CHAR) ,
    login    VARCHAR2 (64 CHAR) NOT NULL ,
    haslo    VARCHAR2 (32 CHAR) NOT NULL
  ) ;
ALTER TABLE Pracownik ADD CONSTRAINT Pracownik_PK PRIMARY KEY ( ID ) ;
ALTER TABLE Pracownik ADD CONSTRAINT Pracownik_PESEL_UN UNIQUE ( PESEL ) ;

CREATE TABLE Projekt
  (
    ID        INTEGER NOT NULL ,
    Kod       VARCHAR2 (16 CHAR) ,
    NAZWA     VARCHAR2 (2048 CHAR) NOT NULL ,
    Aktywny   INTEGER DEFAULT 0 NOT NULL ,
    StartDT   DATE NOT NULL ,
    StopDT    DATE ,
    Uwagi     VARCHAR2 (2048 CHAR) ,
    Klient_ID INTEGER NOT NULL
  ) ;
ALTER TABLE Projekt ADD CONSTRAINT ProjActive CHECK ( Aktywny IN (0, 1)) ;
COMMENT ON COLUMN Projekt.ID
IS
  'Id projektu' ;
  COMMENT ON COLUMN Projekt.NAZWA
IS
  'Nazwa projektu' ;
  COMMENT ON COLUMN Projekt.StartDT
IS
  'Data rozpoczêcia projektu' ;
  COMMENT ON COLUMN Projekt.StopDT
IS
  'Data zakoñczenia projektu' ;
  ALTER TABLE Projekt ADD CONSTRAINT Projekt_PK PRIMARY KEY ( ID ) ;

CREATE TABLE Zadanie
  (
    ID         INTEGER NOT NULL ,
    Kod        VARCHAR2 (16) ,
    Nazwa      VARCHAR2 (2048 CHAR) NOT NULL ,
    Aktywny    INTEGER DEFAULT 0 NOT NULL ,
    Estymacja  INTEGER ,
    StartDT    DATE NOT NULL ,
    StopDT     DATE ,
    Uwagi      VARCHAR2 (2048 CHAR) ,
    Projekt_ID INTEGER NOT NULL
  ) ;
ALTER TABLE Zadanie ADD CONSTRAINT ZadActive CHECK ( Aktywny IN (0, 1)) ;
ALTER TABLE Zadanie ADD CONSTRAINT Zadanie_PK PRIMARY KEY ( ID ) ;

ALTER TABLE Czas_Pracy ADD CONSTRAINT Czas_Pracy_Pracownik_FK FOREIGN KEY ( Pracownik_ID ) REFERENCES Pracownik ( ID ) ;

ALTER TABLE Czas_Pracy ADD CONSTRAINT Czas_Pracy_Pracownik_FK_INSP FOREIGN KEY ( INSP ) REFERENCES Pracownik ( ID ) ;

ALTER TABLE Czas_Pracy ADD CONSTRAINT Czas_Pracy_Pracownik_FK_MODP FOREIGN KEY ( MODP ) REFERENCES Pracownik ( ID ) ;

ALTER TABLE Czas_Pracy ADD CONSTRAINT Czas_Pracy_Zadanie_FK FOREIGN KEY ( Zadanie_ID ) REFERENCES Zadanie ( ID ) ;

ALTER TABLE Projekt ADD CONSTRAINT Projekt_Klient_FK FOREIGN KEY ( Klient_ID ) REFERENCES Klient ( ID ) ;

ALTER TABLE Zadanie ADD CONSTRAINT Zadanie_Projekt_FK FOREIGN KEY ( Projekt_ID ) REFERENCES Projekt ( ID ) ;



CREATE SEQUENCE czas_pr_seq
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE pracownik_seq
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;  
  
CREATE SEQUENCE zadanie_seq
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;   
  
CREATE SEQUENCE projekt_seq
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;   
  
CREATE SEQUENCE klient_seq
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;    


CREATE OR REPLACE TRIGGER cz_pr_seq_trig
BEFORE INSERT ON czas_pracy
FOR EACH ROW
BEGIN
	IF :new.id IS NULL THEN
		SELECT czas_pr_seq.nextval INTO :new.id FROM DUAL;
	END IF;
END;  
/

CREATE OR REPLACE TRIGGER prac_seq_trig
BEFORE INSERT ON pracownik
FOR EACH ROW
BEGIN
	IF :new.id IS NULL THEN
		SELECT pracownik_seq.nextval INTO :new.id FROM DUAL;
	END IF;
END;  
/

CREATE OR REPLACE TRIGGER zad_seq_trig
BEFORE INSERT ON zadanie
FOR EACH ROW
BEGIN
	IF :new.id IS NULL THEN
		SELECT zadanie_seq.nextval INTO :new.id FROM DUAL;
	END IF;
END;  
/

CREATE OR REPLACE TRIGGER proj_seq_trig
BEFORE INSERT ON projekt
FOR EACH ROW
BEGIN
	IF :new.id IS NULL THEN
		SELECT projekt_seq.nextval INTO :new.id FROM DUAL;
	END IF;
END;  
/

CREATE OR REPLACE TRIGGER klient_seq_trig
BEFORE INSERT ON klient
FOR EACH ROW
BEGIN
	IF :new.id IS NULL THEN
		SELECT klient_seq.nextval INTO :new.id FROM DUAL;
	END IF;
END; 
/

CREATE OR REPLACE TRIGGER czas_pracy_insd_trig
BEFORE INSERT ON czas_pracy
FOR EACH ROW
BEGIN

		:new.insd := sysdate;
    :new.modd := sysdate; 
END; 
/

CREATE OR REPLACE TRIGGER czas_pracy_modd_trig
BEFORE UPDATE ON czas_pracy
FOR EACH ROW
BEGIN
	:new.modd := sysdate; 
END; 
/


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
